language: java
# before_install:
#   - chmod +x mvnw
install:
  - mvn clean install -DskipTests
#   - mvn test -DskipTests
script: true
after_success:
  - bash <(curl -s https://codecov.io/bash) -t "ef791045-2066-4cd5-ad42-b6703bed9080"
